### ISSUE TITLE
Ensure the code and the build runs in Java-10+ (OpenJDK) environments

### ISSUE THREAD

**Issue by mawiesne** [rzo1/zlibsvm#1]
Things are moving fast towards Java 11. So we should make things compatible soon.

I scanned the current `pom.xml` of `1.3-SNAPSHOT` and saw it still is at compiler level 1.8. Therefore, dear @rzo1, take according measures to bring _zlibsvm_ to Java10+.

In particular, check the Maven plugin versions.

**Comment by rzo1** [comment]
76c6052be1aa9355e17789be2d8c8621a7eac97d updates `travis.yml` to build the project in several ways, see https://travis-ci.org/rzo1/zlibsvm

Plugins are already up2date.

However, compiler target will be **1.8** for compatibility reasons for now. We will change this in September after Java 11 LTS release.
